### ISSUE TITLE
Panic with calculator example

### ISSUE THREAD

**Issue by anfractuosity** [dwrensha/capnp-rpc-rust#7]
With the calculator example occasionally with the callback part I get a panic:

```
./calculator client 127.0.0.1:8080
Evaluating a literal... 
PASS
Using add and subtract... 
PASS
Pipelining eval() calls... 
PASS
Defining functions... 
PASS
Using a callback... 
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "aborted"', ../src/libcore/result.rs:731
```

**Comment by dwrensha** [comment]
Yep, looks like it can even happen on the easier testcases:

```
Evaluating a literal... 
PASS
Using add and subtract... 
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "aborted"', ../src/libcore/result.rs:731
```

**Comment by dwrensha** [comment]
Thanks for the report. This is fixed by https://github.com/dwrensha/capnp-rpc-rust/commit/6ec440dea3965134b3dd4b8cac32997d7d12614b.
